### ISSUE TITLE
Generalize MetroHash: Init, Hash1, Hash2, HashX, Finalize

### ISSUE THREAD

**Issue by arthurprs** [jandrewrogers/MetroHash#1]
Hello I was porting MetroHash to rust today and I found a limitation. In the current form the algorithm only hashes input in one shot. I can't for example:

```
hasher = MetroHasher(seed)
hasher.hash(333)
hasher.hash(444)
hash = hasher.finalize()
```

I'm not an hash expert but combining the hashes in succession (the only possible way right now) will kill the hash quality rapidly as there's effective no internal state shared between the calls.

Is this assessment correct? Am I missing something.

**Comment by robertklep** [comment]
It's actually something that I could use for my [Node.js](https://github.com/robertklep/node-metrohash) implementation (streams of data are quite common in Node, so having the option to update would mean that it won't be necessary to read all the data into memory first).

Cryptographic hashes in Node are set up in the same way (see [this](https://nodejs.org/api/crypto.html#crypto_class_hash), if you're interested).

**Comment by arthurprs** [comment]
I think replacing the *seed* argument with an *initial* hash value would suffice more now (we need to change it's size to match the hash output size though).

@jandrewrogers Can you advise?

**Comment by jandrewrogers** [comment]
Arthur, it is straightforward to create an incremental version along the lines of an "Init, Hash, ... , Finalize" pattern that is identical to the one-shot version by persisting a 32-byte buffer and a small amount of additional state. I will take a look at adding this variation as simple C++ classes tomorrow.

**Comment by jandrewrogers** [comment]
My initial assessment was incorrect. Due to the length being part of the internal register initialization in these particular functions, they cannot be made incremental. However, it is trivial to eliminate this problem by generating a new set of (structurally) nearly identical functions with that constraint.

I am already generating a new set of high-quality incremental-izable functions that are actually very marginally faster. These will be added as new classes with both incremental and one-shot interfaces.

**Comment by arthurprs** [comment]
Sounds neat. Looking forward to update my Rust port with it.

**Comment by jandrewrogers** [comment]
Added new 64-bit and 128-algorithms that are fully incremental (and slightly superior). These are organized in classes that support both incremental and stateless hash construction. The classes have test vectors built in and a static method for verifying the implementation against those tests. 

An incremental 128-bit CRC algorithm is on the way but I ran out of time to get the implementation finished up and tested.

**Comment by robertklep** [comment]
Great! I updated [my Node.js module](https://github.com/robertklep/node-metrohash) accordingly.

**Comment by arthurprs** [comment]
This is neat, I'll update by Rust with it.

**Comment by arthurprs** [comment]
I'm going to close this as it was fixed a long time ago 😆
